### ISSUE TITLE
export button

### ISSUE THREAD

**Issue by pknight03** [Zibethin/sims-activation#4]
Should there be a button where the raw data can be exported?

**Comment by pknight03** [comment]
Amazing - but I get "Error load csv please contact the website administrator"

**Comment by Zibethin** [comment]
Is that on citric?

Sent from Mail on Android 
 
  On Wed, 8 Feb 2017 at 9:42, pknight03<notifications@github.com> wrote:   
Amazing - but I get "Error load csv please contact the website administrator"
